### ISSUE TITLE
Switching online a nonexistent dasd device

### ISSUE THREAD

**Issue by poncovka** [storaged-project/libblockdev#153]
When the `bd_s390_dasd_online` function from `s390.c` is called and the device with the given number does not exist, the function returns `false` without a message (an exception in Python).

Usage:
```
try:
  if not blockdev.s390.dasd_online(device):
    error = "The device could not be switched online. It may not exist."
except blockdev.S390Error as e:
  error = str(e)
```

**Comment by vpodzime** [comment]
This needs a bit debugging on the actual s390 HW.

**Comment by vojtechtrefny** [comment]
I've tested this on a s390 machine and I wasn't able to reproduce this:

```
In [2]: BlockDev.s390.dasd_online("aaaaaaa")
S390Error: Could not open device aaaaaaa even after removing it from the device ignore list.
```

I've checked the code and I don't see a path that could return `FALSE` and not set the error. It is possible this was fixed by some other changes.

**Comment by poncovka** [comment]
It seems to work now, so I have removed the workaround from Anaconda: https://github.com/rhinstaller/anaconda/pull/1731
