### ISSUE TITLE
Progress report using file descriptor

### ISSUE THREAD

**Issue by jtulak** [storaged-project/libblockdev#307]
Hi guys,
I looked into the possibility of providing a progress report for longer-running operations. For tools from e2fsprogs, it should be really easy, because e2fsprogs tools can print its progress into a file descriptor passed through CLI arguments on startup: `e2fsck -f -n -C 3 DEVICE` where `3` is a fd opened beforehand.

However, there is an issue with how libblockdev executes commands. It uses glib's `spawn_...` calls, which, by default, closes all file descriptors except stdin/out/err. There is a flag `G_SPAWN_LEAVE_DESCRIPTORS_OPEN` to change that behavior, and I wrote a test/example in https://github.com/jtulak/fd-issue/tree/master

I realize that leaving all descriptors open is a security issue, and I'm not aware of a way how to keep some specific descriptors open in glib. However, I'm not well-versed enough in glib to be sure. It is also possible to use stdout/stderr for the progress report, which might be a solution, but being able to not mess with stdout would be beneficial if it can be done without worsening security. So, is there any other way than mixing the progress with stdout?

Thanks,
Jan

**Comment by vpodzime** [comment]
The only other way coming to my mind is to create a named pipe in ``/tmp`` or somewhere and use it for communication between the processes. However, I don't think it's any safer than leaving the FDs open.

**Comment by vpodzime** [comment]
I believe this is now addressed.
