### ISSUE TITLE
Regression tests

### ISSUE THREAD

**Issue by bdubbs** [storaged-project/libblockdev#310]
So how do you run the regression tests?  

tests/README.rst says "See the chapter `Testing libblockdev' in the docs/ directory or on-line at http://rhinstaller.github.io/libblockdev/"

There is nothing I can find in the docs/ library that is appropriate.

http://rhinstaller.github.io/libblockdev/ gives a 404.

**Comment by bdubbs** [comment]
Note that all 16 tests fail for me when I run 'make test'.  I get messages like:

ImportError: Failed to import test module: utils_test
FileNotFoundError: [Errno 2] No such file or directory: 'journalctl' (I am not using systemd)
ImportError: Failed to import test module: part_test
ImportError: Failed to import test module: s390_test
ImportError: Failed to import test module: swap_test

**Comment by vpodzime** [comment]
Thanks for the heads-up! Both that file and the particular section in documentation (on the right location) need to be updated. We will take care of it ASAP.

**Comment by vojtechtrefny** [comment]
bdubbs: I've fixed the link and added some information about the script we use to run the tests in #311. But running `make test` should work -- what distribution are you using?

**Comment by vpodzime** [comment]
#311 is now merged and the online documentation is updated. @bdubbs, let us know if you are still running into any issues using the updated instructions.

**Comment by bdubbs** [comment]
I am using LFS.  With your updated documentation I was able to get farther,  I had to reinstall python modules pygobject and dbus-python.  Now I get:

Ran 92 tests in 1.276s
FAILED (errors=160, skipped=6)

I do not have python3-pylint yet.  I also do not have mdadm, dmraid, or bcachefs installed,  The package builds fine without them, but the tests indicate an error if they are not installed.  

Our users generally run tests as a sanity check for their build and are not normally developers or programmers.  

My current test log is at http://anduin.linuxfromscratch.org/~bdubbs/files/libblockdev-tests.log

Our current build instructions are at http://www.linuxfromscratch.org/blfs/view/svn/general/libblockdev.html

It would be useful to know what python modules are needed to run the tests so we can add them to BLFS.

I do find some of your messages confusing.  For instance the log says:

1.  "Kernel module 'btrfs' not available", but I do have btrfs built into the kernel, just not as a module.  

2. "The 'mkswap' utility is not available".  But it is available on the path: 
 $ which mkswap
/sbin/mkswap
Same for several other utilities.

3. "Verify that checking the minimum swap utils versions works as expected ...
** (process:13802): WARNING **: Too low version of mkswap: 2.22.1. At least 2.23.2 required." but:
$ mkswap -V
mkswap from util-linux 2.31

**Comment by vpodzime** [comment]
> It would be useful to know what python modules are needed to run the tests so we can add them to BLFS.

[This](https://paste.fedoraproject.org/paste/Okk-eOUf4eNJkk6CuGQZIA) is an ansible playbook we are using to setup machines for running *libblockdev* tests.

**Comment by vpodzime** [comment]
> "Kernel module 'btrfs' not available", but I do have btrfs built into the kernel, just not as a module.

We have just introduced this check recently. And looks like we need to improve it because it didn't occur to us that somebody can have btrfs built into their kernel. I've just created the issue #314 for this.

**Comment by vpodzime** [comment]
> "The 'mkswap' utility is not available". But it is available on the path:
> $ which mkswap
> /sbin/mkswap
> Same for several other utilities.
> 
> "Verify that checking the minimum swap utils versions works as expected ...
> ** (process:13802): WARNING **: Too low version of mkswap: 2.22.1. At least 2.23.2 required." but:
> $ mkswap -V
> mkswap from util-linux 2.31

Some tests intentionally hide some utilities or provide placeholders with lower versions to test that the checking mechanisms work. So these are expected warnings triggered when some tests are run.

**Comment by bdubbs** [comment]
Thank you for the list of dependencies.  I'll see what I can do to make sure they are all available for us.

For your tests, you might want to consider  labeling the results as SKIP instead of ERROR if dependencies are not available.

**Comment by vpodzime** [comment]
> For your tests, you might want to consider labeling the results as SKIP instead of ERROR if dependencies are not available.

We are already doing this with some tests, but yeah, we should do better.

**Comment by vpodzime** [comment]
Btw, #314 is now resolved and we also added [a Vagrantfile template](https://github.com/storaged-project/libblockdev/blob/master/misc/Vagrantfile.tmpl) for an easy way to get a devel/test machine and also for people to easily find which dependencies are required for the tests.

I think things are in a pretty good shape now regarding issues reported here. Feel free to reopen the issue, if you disagree.
