### ISSUE TITLE
Do not require the 'btrfs' module if 'btrfs' is built-in in the kernel

### ISSUE THREAD

**Issue by vpodzime** [storaged-project/libblockdev#314]
In such cases *btrfs* is available even if no such module exists.

**Comment by dwlehman** [comment]
In that case btrfs should appear in `/proc/filesystems`.

**Comment by avleen** [comment]
Hi folks, I was wondering if there's any traction on this, or if there's anything I can do to help it along?
We're running into this problem at the moment when trying to build the latest Anaconda, which depends on libblockdev, and we exclusively use btrfs on some systems.

**Comment by vpodzime** [comment]
I can take a look at this next week.

**Comment by avleen** [comment]
Thank you!!

**Comment by avleen** [comment]
Good news! Turns out we have a patch which works :)
We'll open a PR this week!
