### ISSUE TITLE
cross-compilation to musl fails to find dmraid.h

### ISSUE THREAD

**Issue by maxice8** [storaged-project/libblockdev#331]
[LOG](https://gist.githubusercontent.com/maxice8/c1922ca0bb2bef61d657802b9568bb4c/raw/342768dd9c0ae67728a16e4259f0eee71f591b3a/gistfile1.txt)

relevant part

```
checking for DEVMAPPER... yes
Checking header dmraid/dmraid.h existence and usability...In file included from /usr/x86_64-linux-musl/usr/include/dmraid/lib_context.h:16:0,
                 from /usr/x86_64-linux-musl/usr/include/dmraid/dmraid.h:20,
                 from /tmp/7outv.c:1:
/usr/x86_64-linux-musl/usr/include/dmraid/misc.h:37:35: error: unknown type name 'loff_t'; did you mean 'off_t'?
        void *buffer, size_t size, loff_t offset);
                                   ^~~~~~
                                   off_t
/usr/x86_64-linux-musl/usr/include/dmraid/misc.h:39:36: error: unknown type name 'loff_t'; did you mean 'off_t'?
         void *buffer, size_t size, loff_t offset);
                                    ^~~~~~
                                    off_t
no

*** Libblockdev encountered the following issues during configuration:

dmraid.h not available
```

**Comment by vojtechtrefny** [comment]
This is problem in libdmraid, not in libblockdev. We are just checking if libdmraid is available and because it doesn't support pkgconf we are doing it this way.

If you are trying to package libblockdev because udisks depends on it, you can configure it without the dm plugin (using `--without-dm`), udisks doesn't depend on it.

**Comment by maxice8** [comment]
On Thu, Mar 22, 2018 at 04:57:52AM -0700, Vojtech Trefny wrote:
> This is problem in libdmraid, not in libblockdev. We are just checking if
> libdmraid is available and because it doesn't support pkgconf we are doing it
> this way.
> 
> If you are trying to package libblockdev because udisks depends on it, you can
> configure it without the dm plugin (using --without-dm), udisks doesn't depend
> on it.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

ooh, yes i'm trying to bump udisks2 it changed API and update checker broke, thanks for the tips!

**Comment by vpodzime** [comment]
There's nothing that should be done for this issue in *libblockdev*. Closing.
