### ISSUE TITLE
libblockdev fails to build, 'libvolume_key.h not available'

### ISSUE THREAD

**Issue by TimB87** [storaged-project/libblockdev#333]
Hey, 
I'm trying to build libblockdev 2.16 (or git) with crypto support, I have installed volume_key 0.3.9 in the same prefix (=/usr), but configure aborts with libvolume_key.h not available.
Can somebody help me out here?

Log:
+ cd libblockdev-2.16
+ ./configure --prefix=/usr --without-lvm_dbus --without-dm --without-lvm --without-bcache --without-gtk-doc
[..]
*** Libblockdev encountered the following issues during configuration:

libvolume_key.h not available

*** Libblockdev will not successfully build without these missing dependencies
=======> ERROR: Building '/home/pkgmk/packages/libblockdev#2.16-1.pkg.tar.gz' failed.

# ls -la /usr/include/volume_key/libvolume_key.h 
-rw-r--r-- 1 root root 14890 Mär 25 13:19 /usr/include/volume_key/libvolume_key.h
# ls -la /usr/lib/libvolume_key.*                                                 
-rwxr-xr-x 1 root root   1231 Mär 25 13:19 /usr/lib/libvolume_key.la
lrwxrwxrwx 1 root root     22 Mär 25 13:19 /usr/lib/libvolume_key.so -> libvolume_key.so.1.2.2
lrwxrwxrwx 1 root root     22 Mär 25 13:19 /usr/lib/libvolume_key.so.1 -> libvolume_key.so.1.2.2
-rwxr-xr-x 1 root root 101392 Mär 25 13:19 /usr/lib/libvolume_key.so.1.2.2

**Comment by vpodzime** [comment]
Doesn't the output from ``./configure`` tell something more? I mean, in the part where it checks for the library/headers.

**Comment by TimB87** [comment]
Hey,
this is the complete output: https://pastebin.com/2dsde4kw

**Comment by vpodzime** [comment]
Could you please test if #334 fixes the issue for you, @TimB87? Thanks!

**Comment by TimB87** [comment]
I am not that familiar with git yet, so I created patch file with your change and patched it against 2.16, no change so far.
https://pastebin.com/JpA39rKw
I'll try with the git version next.

**Comment by TimB87** [comment]
Seems to work!
=======> New files found:
NEW       -rw-r--r--      root/root       usr/include/blockdev/crypto.h
NEW       -rwxr-xr-x      root/root       usr/lib/libbd_crypto.la
NEW       lrwxrwxrwx      root/root       usr/lib/libbd_crypto.so -> libbd_crypto.so.2.0.0
NEW       lrwxrwxrwx      root/root       usr/lib/libbd_crypto.so.2 -> libbd_crypto.so.2.0.0
NEW       -rwxr-xr-x      root/root       usr/lib/libbd_crypto.so.2.0.0
=======> Building '/home/pkgmk/packages/libblockdev#git-1.pkg.tar.gz' succeeded.

**Comment by vpodzime** [comment]
Great, thanks!
