### ISSUE TITLE
bd_fs_xfs_check  should use xfs_repair -n

### ISSUE THREAD

**Issue by sandeen** [storaged-project/libblockdev#344]
bd_fs_xfs_check  today uses xfs_db:

https://github.com/storaged-project/libblockdev/blob/686756bbe0663582788be903d05f7f15b28ae9e9/src/plugins/fs/xfs.c#L154

but it really should just use xfs_repair -n; xfs_db's check command does not scale for large filesystems, and is really only a debug tool in xfs_db, not something for general use.  xfs_repair -n will return 0/1 depending on clean/dirty and it should be used similarly to how the ext code uses e2fsck -n to check the filesystem.

**Comment by vpodzime** [comment]
Thanks for the tip, @sandeen! I will submit a PR changing this.

**Comment by vpodzime** [comment]
@sandeen, please see #345, the tests failed on all the testing systems. Probably due to this:
> Regardless, the filesystem to be repaired must be unmounted, otherwise, the resulting filesystem may be inconsistent or corrupt.

I guess? So in practice *xfs_repair -n* doesn't work as good as the original solution for us.

**Comment by sandeen** [comment]
I can't tell how those tests are failing ("false is not true?"), but neither repair nor check is valid to run against a mounted block device...

**Comment by sandeen** [comment]
This:

https://github.com/storaged-project/libblockdev/blob/686756bbe0663582788be903d05f7f15b28ae9e9/tests/fs_test.py#L563-L567

is worrisome, it's never valid to check a mounted filesystem.  I don't know why xfs_db -c check would have worked before, it should also fail:

```
# xfs_db -c check /dev/loop0
xfs_db: /dev/loop0 contains a mounted filesystem

fatal error -- couldn't initialize XFS library
```

but it's simply not a valid test to try to consistency-check a mounted block device from userspace.

**Comment by djwong** [comment]
xfs_check and xfs_repair are not currently and have never been supported on a mounted filesystem. We will some day (soon) provide online fsck, but in the meantime there is no way to check metadata on a live fs.

**Comment by sandeen** [comment]
Any update on this?  I'm concerned that the library thinks it can fsck mounted filesystems...

**Comment by vpodzime** [comment]
> Any update on this? I'm concerned that the library thinks it can fsck mounted filesystems...

I will update the tests and documentation in that PR I submitted.

**Comment by vpodzime** [comment]
So I thought I'd modify the test to make sure the function call raises an error on a mounted file system. However, the exit code is just ``1`` if the file system is mounted. So the same exit code as if the file system is not clean. This is really unfortunate.

**Comment by vpodzime** [comment]
I ended up changing the documentation that the function now reports an unclean FS if it is mounted RW. Because, and that's another interesting thing, a RO mount is okay. So the test was modified to do a RO mount when calling the check() function.
