### ISSUE TITLE
Make sure last enum values don't change when adding new ones before them

### ISSUE THREAD

**Issue by vpodzime** [storaged-project/libblockdev#351]
For example in #350, new enum values are added. Which means ``BD_NVDIMM_NAMESPACE_MODE_UNKNOWN``, which should logically be last, now is a different integer value which is an ABI change. We should avoid this in the future by:

a) assign the enum values like the above one some high integer that won't change or
b) assign all enum values explicit integer values using high values for the values that should stay last.

**Comment by tbzatek** [comment]
Agreed, we should make this consistent across all plugins. Now that we have unique chance for 3.0...

**Comment by tbzatek** [comment]
c) assign error/invalid/unknown lowest values first

Inspiration: https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gioenums.h

**Comment by tbzatek** [comment]
The LVM VDO API in `lvm.h` seems to be using 255 for last values:

https://github.com/storaged-project/libblockdev/blob/1c948e5054d3771dc73b3bbeec6fa335cda47f22/src/plugins/lvm.h#L43-L71
