### ISSUE TITLE
Progress reporting for ext4 check/repair

### ISSUE THREAD

**Issue by pothos** [storaged-project/libblockdev#354]
Hello,

on my system the progress is not detected. But I'm not sure why, can somebody confirm that it is actually working with e2fsprogs in a version similar to 1.44.2-1 (Debian sid)? I.e. run https://github.com/jtulak/fd-issue and see lines with `Progress: xx%`.

Thanks a lot,

Kai

**Comment by vojtechtrefny** [comment]
Tested on Debian testing (e2fsprogs 1.44.2-1) and it works.

**Comment by pothos** [comment]
Ok, maybe my test image is too small, thanks.
