### ISSUE TITLE
Provide better way to skip "broken" tests

### ISSUE THREAD

**Issue by vojtechtrefny** [storaged-project/libblockdev#371]
The `@skip_on` decorator is useful for tests that should be skipped "forever" -- e.g. to skip bcache tests on CentOS 7 because bcache is not available there -- but it causes a lot of mess when skipping some tests only temporarily because new version of bcache is broken on rawhide. For example some of our LVM tests are skipped on Fedora 27 because LVM is/was broken on rawhide:

`@skip_on("fedora", "27", reason="LVM is broken in many ways on rawhide")`

It might be better to create some "blacklist" file for these cases. The "filtering" itself could be part of the `run_tests.py` script.

With all these "temporary" skips in one place it should be easier to manage them a quickly spot all the "deprecated" skips. It should be also possible to easily run the tests without the skips and (automatically) check if is still needed to skip the test etc.

**Comment by vojtechtrefny** [comment]
I've played a little with the unittest module and functionality it provides and I've created this "simple" example of skipping tests based on tags and a blacklist:

https://gist.github.com/vojtechtrefny/45b9e785744ecdf173089ef8c19acb83

Tests can be tagged using one (or more) of the `TestTags` and will be skipped based on user preference (command line arguments for the `run_tests.py` script, environmental variables etc.).
Test that should be skipped "temporarily" -- e.g. on rawhide -- can be added to the blacklist -- this can be a simple config file with test name, reason and skip condition (distro and/or version). Changing just the config file should be more flexible than changing the tests. The config can even be located only on our testing machines and not in the git.

Tests are actually not skipped using `skipTest` (or similar unittest function) but simply ignored and not added to the `unittest.TestSuite`. And I think this is actually better -- the "skipped" information is usually not really helpful and with the tags and blacklist we want to skip the tests, so it shouldn't be necessary to inform user that we skipped some tests.
This also allows us to actually run only tests with some tag -- e.g. we can run the unstable tests separately and actually see/check the results instead of silently ignoring it with "unstable-fail ok". And we can also select a subset of "basic/stable" tests to run in something like [Fedora CI](https://fedoraproject.org/wiki/CI/Tests).

It should be also possible to create a custom `unittest.TestRunner` with custom output (html or something that is more readable and easier to navigate).

Downside of this approach is that it is quite "hacky" -- adding extra attributes to functions using a decorator is definitely not nice and extracting the individual test functions from the `unittest.TestLoader` is also very complicated.

@vpodzime @tbzatek thoughts?

**Comment by vpodzime** [comment]
> it shouldn't be necessary to inform user that we skipped some tests

I think it's sometimes useful information. We can still easily add a little summary to the end.


> Downside of this approach is that it is quite "hacky"

I don't think this is a problem. The Python's unittest framework is just bad. Everything we have wanted to do ended up being a hack because it was impossible to do it in a nice way. And as long as we hide the ugly things from the "users" (non-core contributors), it's not a problem.

**Comment by vojtechtrefny** [comment]
Fixed by #432 432
