### ISSUE TITLE
Switch to runtime dependency checks by default

### ISSUE THREAD

**Issue by vojtechtrefny** [storaged-project/libblockdev#423]
Currenctly libblockdev checks all dependencies during `init`. With more new runtime dependencies, this is no longer the best option, especially for plugins like `fs` with many dependencies that are not always available (like *ntfsprogs*). That's why we have option to run the checks only during runtime if user actually tries to run function that needs some of the dependencies. We should switch to this behaviour by default and keep init checks optional.

**Comment by tbzatek** [comment]
FYI the checks in `master/src/plugins/fs.c:bd_fs_check_deps()` looks weird - the `ret = ret && bd_fs_xfs_is_tech_avail(...)` tests will always fail if `ret` is already `FALSE`.

I'm somewhat missing the point here, failing to understand usefulness of the return value. My suggestion is to do somewhat deeeper refactoring here...
