### ISSUE TITLE
Remove method fails for DBus

### ISSUE THREAD

**Issue by Queuecumber** [storaged-project/libblockdev#453]
Currently getting the following error when calling `lvm_lvremove`

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/targetd/main.py", line 115, in do_POST
    result = mapping[method](self, **params)
  File "/usr/local/lib/python3.6/dist-packages/targetd/block.py", line 175, in destroy
    bd.lvm.lvremove(vg_name, name, False)
  File "/usr/lib/python3/dist-packages/gi/overrides/BlockDev.py", line 824, in wrapped
    raise transform[1](msg)
gi.overrides.BlockDev.LVMError: Failed to call the 'Remove' method on the '/com/redhat/lvmdbus1/Lv/25' object: GDBus.Error:org.freedesktop.DBus.Python.ValueError: ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

Other methods seem to be working fine, using the lvm tools API works fine its only the DBus API that fails.

Pyhton code the produces the error:

```
bd.lvm.lvremove(vg_name, name)
```

**Comment by vojtechtrefny** [comment]
I've tested this manually and lvremove works for me, I also didn't see similar problem in our tests. What version of libblockdev and lvm do you have (and what distribution are you using)? Is this a "normal" linear LV or some "special" configuration/type?

**Comment by Queuecumber** [comment]
* Ubuntu 18.10
* thinly provisioned volume
* libblockdev 2.16-2
* libblockdev-lvm-dbus2 2.16-2
* lvm 2.02.176-4.1ubuntu3.18.10.1
* dbus 1.12.10-1ubuntu2.1
* lvm2-dbusd 2.02.176-4.1ubuntu3.18.10.1

All whatever is in the ubuntu packges by default. 

I also testing running the remove method through D-Feet and it worked fine

**Comment by vojtechtrefny** [comment]
Thanks, this was fixed in #415. Unfortunately Ubuntu doesn't have the newest version. As a workaround you can switch to the cli LVM plugin that uses command line utility instead of the DBus API.

```
from gi.repository import BlockDev

lvm_plugin = blockdev.PluginSpec() 
lvm_plugin.name = blockdev.Plugin.LVM 
lvm_plugin.so_name = "libbd_lvm.so.2"

# inicialization with LVM plugin only
BlockDev.init((lvm_plugin,))
```

(Both plugins provide the same API, just the backend is different.)

**Comment by vpodzime** [comment]
I believe this can be closed now. (feel free to add comments and questions @Queuecumber)

**Comment by Queuecumber** [comment]
Got it sorry for the noise
