### ISSUE TITLE
gi.repository.BlockDev' object has no attribute 'plugin_specs_from_names

### ISSUE THREAD

**Issue by Queuecumber** [storaged-project/libblockdev#454]
I'm getting this error in Docker containers for recent Ubuntu versions, I tried 18.04, 18.10, and 19.04. The weird thing is that I use this on a bare metal ubuntu 18.10 install without any problems. 

When I open a python interpreter and look at the `BlockDev` object, the only method that seems to be missing is the `plugin_specs_from_names` method. Everything else seems to be there. Is there any weird dependency I might be missing? I'm currently installing 

```
        python3 
        python3-pip 
        python3-gi 
        libblockdev-dev 
        libblockdev-lvm-dev 
        build-essential
```

**Comment by Queuecumber** [comment]
Turns out the ubuntu package is called `python3-blockdev` the only one that isnt `libblockdev` installing that package gives functional python bindings

**Comment by denvolj** [comment]
If you still encountering same issue using venv, try create it with `--system-site-packages` flag:
`python3 -m venv env --system-site-packages`
