### ISSUE TITLE
Need to deprecate some oversized constants to avoid nonsense in GIR file

### ISSUE THREAD

**Issue by mulkieran** [storaged-project/libblockdev#464]
The constants are:

LVM_MAX_PE_SIZE
LVM_MAX_THPOOL_MD_SIZE

Based on #463, it seems that the introspection tool can not infer a sufficiently wide type for its constants and makes them all gint's (which are defined to be standard width ints, therefore can be 32 bit and are on most machines). These values are both 16 GiB, too large to fit into any 32-bit int). So I guess they should be deprecated in the same way as LVM_MAX_LV_SIZE and functions substituted.

I'm not aware of any other values that are too large for their gir-tool generated types in the libblockdev source.

It seems that the introspection tool is itself a bit broken. Is there any issue or issues about these bugs filed against the tool itself, for reference?

Note that #462, and this issue are a bit different. In the bug described in #462 the value in the gir file is both incorrect _and_ too wide for its specified type; for this bug the values are just too wide for their specified type, they are correct.

**Comment by vojtechtrefny** [comment]
I didn't realize there is more "big" constant that can cause same issue. We'll need to "mark" all constants in the api files using the `G_GUINT64_CONSTANT` macro.
