### ISSUE TITLE
Add a generic function to get filesystem size

### ISSUE THREAD

**Issue by vojtechtrefny** [storaged-project/libblockdev#477]
This will be helpful for UDisks -- it currently has a special function that needs to be edited every time we add support for a new filesystem -- https://github.com/storaged-project/udisks/blob/master/src/udiskslinuxfilesystem.c#L144

Related issue: https://github.com/storaged-project/udisks/pull/700

**Comment by tbzatek** [comment]
UDisks could be ported to this new API within the 2.9.0 cycle now that we're open to more significant changes.
