### ISSUE TITLE
bd_fs_wipe happily wipes mounted filesystems

### ISSUE THREAD

**Issue by mvollmer** [storaged-project/libblockdev#483]
Calling bd_fs_wipe on a block device with a filesystem that is mounted will happily go ahead and remove the signatures.  It should fail with an error.

I think this can be achieved by adding O_EXCL here: https://github.com/storaged-project/libblockdev/blob/29332ce6ba52dc7fcfa193b6ed367ea112fa91c2/src/plugins/fs/generic.c#L124

**Comment by vojtechtrefny** [comment]
Yes, `O_EXCL` will fix this, wipefs is using that -- https://github.com/karelzak/util-linux/blob/master/misc-utils/wipefs.c#L543

But do we want to fix this? There is a use case for wiping mounted devices, wipefs has a `--force` option that doesn't use `O_EXCL` and changing this might be seen as a change of behaviour.
The best solution would be to add a new `force` option to `bd_fs_wipe` but that's an API change.

Thoughts?

**Comment by mvollmer** [comment]
Let's go one level up, to UDisks2.  It used to call wipefs without --force, and then got changed to call bd_fs_wipe, right?

So if the UDisks2 API has regressed in this regard, and we should fix that by having it call bd_fs_wipe with a new "exclusive" option.

Does that make sense?

**Comment by tbzatek** [comment]
Makes sense for both of you. The docs of `bd_fs_wipe()` should be note this fact though. Perhaps introducing a new function such as `bd_fs_wipe_exclusive()` or `bd_fs_wipe_locked()` might do the trick and in UDisks we're fine with bumping `libblockdev` requirement for the 2.9 cycle.

**Comment by vpodzime** [comment]
> The docs of bd_fs_wipe() should be note this fact though. Perhaps introducing a new function such as bd_fs_wipe_exclusive() or bd_fs_wipe_locked() might do the trick and in UDisks we're fine with bumping libblockdev requirement for the 2.9 cycle.

I think this is the right way to go.

**Comment by vpodzime** [comment]
And for libblockdev-3.0, we should add the new argument if we break the API.

**Comment by mvollmer** [comment]
Note that as far as Cockpit is concerned, things are mostly safe.  It will explicitly unmount filesystems before wiping them.

**Comment by vojtechtrefny** [comment]
New function for 2.x: #484

We need to decide about the API change for master/3.0.

**Comment by tbzatek** [comment]
> We need to decide about the API change for master/3.0.

Meaning the 3.0 would remove this new symbol again (and change the arguments)?

**Comment by vojtechtrefny** [comment]
> Meaning the 3.0 would remove this new symbol again (and change the arguments)?

Yes. We didn't decide about breaking API in 3.0 yet, but if we decide to do so we should probably do it here too.
