### ISSUE TITLE
libblockdev architesture

### ISSUE THREAD

**Issue by kloczek** [storaged-project/libblockdev#525]
This ticket is not per se issue. I more about some thoughts about current libblockdev  architecture.

Currently libblockdev has kind of modular architecture and  that architecture IMO have some drawbacks:
1) it is modular beyond actual needs
2) it is not possible to build support for some functionalities as linked into libblockdev
3) it is not possible to build it as monolithic library

Will try to explanation to each of above
1) Looking on Fedora/Redhat package is possible to see that almost every module is packed into separated module. At the same time utisk2 package on list of fixed dependencies has:
```
Requires:       libblockdev        >= %{libblockdev_version}
Requires:       libblockdev-part   >= %{libblockdev_version}
Requires:       libblockdev-loop   >= %{libblockdev_version}
Requires:       libblockdev-swap   >= %{libblockdev_version}
Requires:       libblockdev-mdraid >= %{libblockdev_version}
Requires:       libblockdev-fs     >= %{libblockdev_version}
Requires:       libblockdev-crypto >= %{libblockdev_version}
```
So there is some core functions which cannot be skipped and current modularisation adds only kind over complexity. In other words placing some functions in separated modules is (IMO) w
aey beyond actual needs :P 

2) all this would be possible to make simpler if it would be possibility to build main libblockdev with linked in exact extension. This would allow as well better optimise actual code and memory size as for example LTO would able to better reduce size of that code and calling some exact function will not require additional jumps over DSO jump table
3) Possibility to build fully nonpolitical architecture would be great for embedded systems. That would open using libblockdev on small those smallest systems as well.

Declaimer: I'm more interested about some thoughts and maybe sharing some plans about some architecture changes which are already maybe nesting in you head :)

**Comment by vojtechtrefny** [comment]
> Looking on Fedora/Redhat package is possible to see that almost every module is packed into separated module. At the same time utisk2 package on list of fixed dependencies has:

UDisks isn't the only user of libblockdev. [Blivet](https://github.com/storaged-project/blivet) also uses it and uses a different subset of plugins (we don't use fs and part plugins in blivet) so selecting a list of "default" plugins would be harder than just looking at what UDisks uses.

> Possibility to build fully nonpolitical architecture would be great for embedded systems. That would open using libblockdev on small those smallest systems as well.

Not sure if monolithic architecture is better for embedded systems. We've been already asked to make mdraid and crypto parts of UDisks optional and that wouldn't be possible without libblockdev being modular.

I generally agree that plugins make libblockdev more complicated and bring some issues, but I think the plugin architecture brings more good things than bad things.

**Comment by kloczek** [comment]
> UDisks isn't the only user of libblockdev. Blivet also uses it and uses a different subset of plugins (we don't use fs and part plugins in blivet) so selecting a list of "default" plugins would be harder than just looking at what UDisks uses.

Don't get me wrong but without those essential subpackages which are listed in some dependencies Blivet  functionalities will be very limited.

>We've been already asked to make mdraid and crypto parts of UDisks optional and that wouldn't be possible without libblockdev being modular.

Nevertheless both are listed as fixed/static dependencies and because of that it is not possible to install that bits optionally.

Ergo: building at least some parts as DSOs does not make to much sense.

IMO the best would be allow to make on decision about building something as DSO or statically linked into libblockdev on source code configuration time. It is not possible as well to build whole libblockdev as static library. Currently it is not possible to do this because only supported way of using libblockdev is as DSO + SO modules.

Yes static libblockdev is better for embedded use cases because is not used DSO jump tables and it is possible to use LTO across many libraries (together).
