### ISSUE TITLE
mkfs.vfat exit code not handled correctly

### ISSUE THREAD

**Issue by hsattler** [storaged-project/libblockdev#550]
Hi,

I use libblockdev via udisks2. In udisks2, I call the Repair method on a vfat USB stick.
If the stick was removed without unmounting before, this will trigger a real repair.

However, fsck.vfat returns with exit code 1. This is expected according to its man page:
0 -> No recoverable errors have been detected.
1 -> Recoverable errors have been detected or dosfsck has discovered an internal inconsistency.

Thus udisks2 always returns an error message.

Please fix the exit code handling....

**Comment by vojtechtrefny** [comment]
Sorry, I didn't realize `fsck.vfat` returns non-zero even when all the errors are fixed. Thank you for the report, #551 should fix this.

**Comment by hsattler** [comment]
For fixing this from outside udisks2, I took a different approach that you also might want to consider:
After repair return an error, I call check again to make sure that the repair worked. The check return with exit code 0 on success.

**Comment by tbzatek** [comment]
That sounds like a good idea, thanks @hsattler!

**Comment by vojtechtrefny** [comment]
Good idea, I've updated the PR. Thanks.
