### ISSUE TITLE
regress after update libblockdev-utils in Fedora 32 liveinst command broken for create partitions automaticaly

### ISSUE THREAD

**Issue by elemc** [storaged-project/libblockdev#566]
Hello, i have problem to install custom Fedora Live image after update libblockdev-utils to version 2.24.
With version 2.23 libblockdev-utils all works fine.
Auto partioning in liveinst failed only on not C locale, ru_RU.UTF-8 as example.
See video, as it look https://youtu.be/WD6JG7tKilA
[alllog.log](https://github.com/storaged-project/libblockdev/files/5238782/alllog.log)
[trace.log](https://github.com/storaged-project/libblockdev/files/5238785/trace.log)

**Comment by vojtechtrefny** [comment]
This is already fixed on master, see https://github.com/storaged-project/libblockdev/pull/544. I unfortunately didn't realize the original bug was also backported to 2.24. I'll do a new libblockdev build ASAP.

**Comment by vojtechtrefny** [comment]
New patched builds of libblockdev are now in Bodhi for all versions of Fedora, I'll do a new upstream release with patch for this and few more next week.

**Comment by elemc** [comment]
Thanks! I will be wait in updates repo.
