### ISSUE TITLE
Remove gdisk dependency

### ISSUE THREAD

**Issue by marcosfrm** [storaged-project/libblockdev#568]
Now that #559 is merged (yay!), `gdisk` dependency can go away.

https://github.com/storaged-project/libblockdev/blob/ea4552b6ecc75cd41e039469fbbb9635b7fbde08/dist/libblockdev.spec.in#L512

And maybe update these too:

https://github.com/storaged-project/libblockdev/blob/ea4552b6ecc75cd41e039469fbbb9635b7fbde08/src/plugins/part.h#L26

https://github.com/storaged-project/libblockdev/blob/ea4552b6ecc75cd41e039469fbbb9635b7fbde08/src/lib/plugin_apis/part.api#L31

**Comment by vojtechtrefny** [comment]
> Now that #559 is merged (yay!)

And it took us only 3 years! :-)

> 
> And maybe update these too:
> 
> https://github.com/storaged-project/libblockdev/blob/ea4552b6ecc75cd41e039469fbbb9635b7fbde08/src/plugins/part.h#L26
> 
> https://github.com/storaged-project/libblockdev/blob/ea4552b6ecc75cd41e039469fbbb9635b7fbde08/src/lib/plugin_apis/part.api#L31

We kept the old flags for backwards compatibility.
