### ISSUE TITLE
e2fsck exit code 1 is not failure

### ISSUE THREAD

**Issue by dtsund-umich** [storaged-project/libblockdev#587]
I was using gnome-disk-utility (gnome-disk-utility 3.36.1
UDisks 2.8.4 (built against 2.8.4)), which uses this library, to repair an ext4 partition.  The repair was successful, but it was reported as a failure because e2fsck ended with exit code 1.  But exit code 1 from e2fsck means "file system errors corrected", not failure; exit code 4 indicates that the file system had errors that were not fixed. Telling gnome-disk-utility to repair the filesystem a second time resulted in a report of success, presumably because e2fsck returned an exit code of 0 the second time.

I reported this as a bug for gnome-disk-utility, and was told it was a bug in this library, so now I'm reporting it here.

**Comment by vojtechtrefny** [comment]
Thank you for the report, fixed in #588 I'll try to do a new minor release soon.
