### ISSUE TITLE
Duplicate LVs returned from bd_lvm_lvs()

### ISSUE THREAD

**Issue by wfpudak** [storaged-project/libblockdev#667]
Hi,

We've noticed that if an LV has several segments as noted by lvdisplay

  --- Logical volume ---
  LV Path                /dev/rootvg/test
  LV Name                test
  VG Name                rootvg
  LV UUID                TgjM5V-jhXX-tPTf-gPMa-c3w6-QEjo-7qkmVg
  LV Write Access        read/write
  LV Creation host, time du1, 2021-10-25 15:59:20 +0000
  LV Status              available
  "#" open                 1
  LV Size                68.00 MiB
  Current LE             68
  **Segments               2**
  Allocation             inherit
  Read ahead sectors     1024
  Block device           253:166

 the API method **bd_lvm_lvs()** will return several entries since **segtype** is used with the **-o** option.

It can easily be reproduced with the lvs command itself as well. This happens due to fragmentation as described in : https://askubuntu.com/questions/380424/understanding-output-of-lvdisplay-in-lvm-linux

Is the expectation from **bd_lvm_lvs()** to return those duplicates or shouldn't the lib code filter them out?

Example lvs output with your flags if there are several segments :

LVM2_VG_NAME=rootvg LVM2_LV_NAME=test LVM2_LV_UUID=TgjM5V-jhXX-tPTf-gPMa-c3w6-QEjo-7qkmVg LVM2_LV_SIZE=71303168 LVM2_LV_ATTR=-wi-ao---- LVM2_SEGTYPE=linear LVM2_ORIGIN= LVM2_POOL_LV= LVM2_DATA_LV= LVM2_METADATA_LV= LVM2_LV_ROLE=public LVM2_MOVE_PV= LVM2_DATA_PERCENT= LVM2_METADATA_PERCENT= LVM2_COPY_PERCENT= LVM2_LV_TAGS=
  LVM2_VG_NAME=rootvg LVM2_LV_NAME=test LVM2_LV_UUID=TgjM5V-jhXX-tPTf-gPMa-c3w6-QEjo-7qkmVg LVM2_LV_SIZE=71303168 LVM2_LV_ATTR=-wi-ao---- LVM2_SEGTYPE=linear LVM2_ORIGIN= LVM2_POOL_LV= LVM2_DATA_LV= LVM2_METADATA_LV= LVM2_LV_ROLE=public LVM2_MOVE_PV= LVM2_DATA_PERCENT= LVM2_METADATA_PERCENT= LVM2_COPY_PERCENT= LVM2_LV_TAGS=
  LVM2_VG_NAME=rootvg LVM2_LV_NAME=new_test LVM2_LV_UUID=jMUqLN-DVYU-RUtV-0TnH-Qczq-L820-Bf2G00 LVM2_LV_SIZE=2097152 LVM2_LV_ATTR=-wi-a----- LVM2_SEGTYPE=linear LVM2_ORIGIN= LVM2_POOL_LV= LVM2_DATA_LV= LVM2_METADATA_LV= LVM2_LV_ROLE=public LVM2_MOVE_PV= LVM2_DATA_PERCENT= LVM2_METADATA_PERCENT= LVM2_COPY_PERCENT= LVM2_LV_TAGS=

**Comment by vojtechtrefny** [comment]
> Is the expectation from bd_lvm_lvs() to return those duplicates or shouldn't the lib code filter them out?

We should definitely not return the LV twice. We might add a function to display the segments in the future, but `bd_lvm_lvs` should filter this out from the `lvs` output.

Note to myself: This can be reproduced simply by creating two linear LVs and resizing the first one to create the two segments.

**Comment by wfpudak** [comment]
Thanks @vojtechtrefny. Locally the workaround was to use lv_layout instead of segtype.
[segtype_to_lv_lay.diff.zip](https://github.com/storaged-project/libblockdev/files/7453879/segtype_to_lv_lay.diff.zip)
e.

**Comment by vojtechtrefny** [comment]
Unfortunately `lv_layout` produces different results for non-linear logical volumes, for example `thin,sparse` instead of `thin` for thin LVs or `thin,pool` instead of `thin-pool` for thin pools so it isn't 1:1 replacement (and we have users that use the strings so we can't change them). I've created #671 as a workaround, that should be good enough for the stable libblockdev, but I think we need some API changes for `BDLVMLVdata` in 3.0, the `segtype` attribute doesn't really make sense.

**Comment by wfpudak** [comment]
Hi @vojtechtrefny ,

Thanks for the explanation we will test your proposed solution.

I noticed some failures on the CI runs for #671. I guess that you plan to merge it but a retrigger/rerun is needed?

Cheers,
/Filip

**Comment by vojtechtrefny** [comment]
The failed `test_lvremove_extra_args` case is addressed in #672

**Comment by vojtechtrefny** [comment]
Closed via #671
