### ISSUE TITLE
Failed to activate swap on /dev/sda: Function not implemented

### ISSUE THREAD

**Issue by tbzatek** [storaged-project/libblockdev#821]
Getting `Failed to activate swap on /dev/sdd: Function not implemented` error from `swapon()` within `bd_swap_swapon()`. Even tried to remove all the code before that, leaving only a simple `swapon()` there. Still fails. No idea what's wrong. Standalone `swapon` works fine. Nothing special in UDisks, no locking.

Opening this issue more or less as a TODO.

**Comment by vojtechtrefny** [comment]
Interesting, `swapon` manpage doesn't even mention `ENOSYS` as one of the possible errnos returned.

**Comment by tbzatek** [comment]
False alarm, this was caused by valgrind, filtering out some syscalls (unimplemented emulation).
