### ISSUE TITLE
NVME Temerature not showed

### ISSUE THREAD

**Issue by wintermute101** [storaged-project/libblockdev#829]
I have 4 hdds and 2 NVME and all have temperature in smart but one is not reported in udisk.

[udisk_dump.txt](https://github.com/storaged-project/libblockdev/files/10280354/udisk_dump.txt)
[nvme0.txt](https://github.com/storaged-project/libblockdev/files/10280358/nvme0.txt)
[nvme1.txt](https://github.com/storaged-project/libblockdev/files/10280359/nvme1.txt)

Probably related to #823 and #568

**Comment by tbzatek** [comment]
Please test the git master versions of `libblockdev` and `udisks`, nvme support is there yet not released.

If you're on Fedora or CentOS Stream, you may use nightly builds from our copr repository: https://copr.fedorainfracloud.org/coprs/g/storage/udisks-daily/

**Comment by tbzatek** [comment]
I'm going to close this for the time being, please reopen if this is still an issue with git master versions (or final releases in couple of months).
