### ISSUE TITLE
Python path detection doesn't work on Debian

### ISSUE THREAD

**Issue by mbiebl** [storaged-project/libblockdev#917]
Version: 3.0
This is basically a clone of https://github.com/storaged-project/libbytesize/issues/111

With the latest release, I now see the python related files being installed as
```
./usr/local/lib/python3.11/dist-packages/gi/overrides/BlockDev.py
```

This is due to feaec37ae5f32b6ae1ff638ceffcef762374df10

**Comment by vojtechtrefny** [comment]
Would the `DEB_PYTHON_INSTALL_LAYOUT="deb"` workaround be usable here as well? That would place the overrides to `/usr/lib/python3/dist-packages/gi/overrides/BlockDev.py` which should be correct.

**Comment by mbiebl** [comment]
Yes, it works here too
