### ISSUE TITLE
co-installability

### ISSUE THREAD

**Issue by mbiebl** [storaged-project/libblockdev#924]
The latest version of libblockdev bump its sonames from 2 → 3.
Yet the file /etc/libblockdev/conf.d/00-default.cfg is not soname qualified, which means both library packages can't be installed in parallel. Is that a deliberate design decision?

By making the libraries co-installable, library transitions become easier.
See also https://www.debian.org/doc/debian-policy/ch-sharedlibs.html#shared-library-support-files

**Comment by mbiebl** [comment]
The file itself is no version independent, as it contains the sonames

**Comment by mbiebl** [comment]
So, while being able to install both libblockdev2 and libblockdev3 side-by-side is likely more of a Debian issue then a Fedora issue, there is another problem, which also affects Fedora afaics:
Let's assume the users edited /etc/libblockdev/conf.d/00-default.cfg and made some changes.
You now upgrade from for v2 to v3. dpkg (and I think rpm as well) will preserve user changes by default, so will keep the old 00-default.cfg, which still uses the old sonames.

Would it be an option to use an API versioned path for the conf.d directory, say `/etc/libblockdev/3/conf.d` ?

**Comment by vojtechtrefny** [comment]
> Yet the file /etc/libblockdev/conf.d/00-default.cfg is not soname qualified, which means both library packages can't be installed in parallel. Is that a deliberate design decision?

Yeah, we didn't realize this would be a problem. I guess it's too late to make the directory versioned. On the other hand libblockdev is a relatively small library with just two users (and only one in Debian) so I think it isn't a big deal to not all having libblockdev2 and libblockdev3 side by side -- we released libblockdev 3.0 together with udisks 2.10 which has a hard requirement on the 3.0 API so I don't expect people will expect to be able to keep using libblockdev 2.x. What do you think?

Any additional thoughts @tbzatek @vpodzime ?

**Comment by mbiebl** [comment]
The co-installability is only one aspect (and yes, with only one consumer the library transition is manageable).
But there is also the issue of the config file containing the soname (see the above comment about manual modifications).

**Comment by vojtechtrefny** [comment]
> The co-installability is only one aspect (and yes, with only one consumer the library transition is manageable). But there is also the issue of the config file containing the soname (see the above comment about manual modifications).

Oh, I see now. Yes, that's definitely a potential problem. I don't expect anyone actually uses the config, but that's probably not enough to ignore the problem. Proposed fix: #926
