### ISSUE TITLE
Remove the configuration files for plugin loading

### ISSUE THREAD

**Issue by vojtechtrefny** [storaged-project/libblockdev#931]
We should investigate possibility of removing the config files in `data/conf.d` that control what plugin type and version will be loaded. I doubt that people are actually using that -- both udisks and blivet are happy with whatever is default except for LVM where we explicitly require the cli plugin -- and it has problems like #926 that we could easily avoid. Thoughts @vpodzime @tbzatek

**Comment by tbzatek** [comment]
I vote for making libblockdev as stateless (in terms of config files) as possible. Defaults can be compiled-in and only overrides can be taken in account from `/etc`.

**Comment by vpodzime** [comment]
Yup, there should be defaults. But I think we should also support the config files to override the defaults.
