### ISSUE TITLE
ntfsresize disable progress bar

### ISSUE THREAD

**Issue by jelly** [storaged-project/libblockdev#963]
While testing filesystem resizing in Cockpit I noticed by default `ntfsresize` enables the progressbar, that leads to some noisy output. Now in Cockpit we should circumvent that people run into this scenario in the first place, however does it not make sense for libblockdev to use `--no-progess-bar` by default? The option has been there [for over 20 years](https://github.com/tuxera/ntfs-3g/commit/c90976e02301612dadd149b390fc2e5ca7461da2#diff-2c62a2bdf78f24c7e2d58d6dc3589852436d9a9124136db9ed9d06e8a23ddd10R249). And I don't see any progress reporting support for resize actions.

![image](https://github.com/storaged-project/libblockdev/assets/67428/36bc58e4-1d28-4e99-b413-58a1e8928360)

**Comment by tbzatek** [comment]
Makes sense, thanks for spotting this!
