### ISSUE TITLE
expected enumeration type void, but got PyBlockDevPlugin instead

### ISSUE THREAD

**Issue by mbiebl** [storaged-project/libblockdev#995]
Running the test suite on Debian sid, I see a lot of those warnings:
```
2367s ** (process:9110): WARNING **: 09:01:02.307: expected enumeration type void, but got PyBlockDevPlugin instead
2367s test_pvresize (lvm_test.LvmTestPVresize.test_pvresize)
2371s Verify that it's possible to resize a PV ... ok
```
Those warnings appear to be benign but they clutter the test output.

A full log is available at
https://ci.debian.net/packages/libb/libblockdev/unstable/amd64/41650426/

**Comment by tbzatek** [comment]
I think that's #987

**Comment by mbiebl** [comment]
I applied #987 to the Debian package. Unfortunately the warnings are not gone.

**Comment by vojtechtrefny** [comment]
Do you have both #987 and #973?

**Comment by mbiebl** [comment]
No, I only had #987. Applying both did fix the warnings.

As this add new API though, I'll wait for an official release. Is there an ETA?
